### ISSUE TITLE
Error on streaming link Button

### ISSUE THREAD

**Issue by IamJithendra** [eyaadh/megadlbot_oss#48]
2020-12-11T06:37:18.764713+00:00 app[web.1]: Traceback (most recent call last):
2020-12-11T06:37:18.764714+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
2020-12-11T06:37:18.764715+00:00 app[web.1]:     await handler.callback(self.client, *args)
2020-12-11T06:37:18.764716+00:00 app[web.1]:   File "/app/mega/telegram/plugins/download.py", line 425, in media_receive_handler
2020-12-11T06:37:18.764717+00:00 app[web.1]:     await m.reply_text(
2020-12-11T06:37:18.764717+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/types/messages_and_media/message.py", line 755, in reply_text
2020-12-11T06:37:18.764717+00:00 app[web.1]:     return await self._client.send_message(
2020-12-11T06:37:18.764718+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/messages/send_message.py", line 121, in send_message
2020-12-11T06:37:18.764718+00:00 app[web.1]:     r = await self.send(
2020-12-11T06:37:18.764718+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
2020-12-11T06:37:18.764719+00:00 app[web.1]:     r = await self.session.send(
2020-12-11T06:37:18.764719+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 441, in send
2020-12-11T06:37:18.764719+00:00 app[web.1]:     return await self._send(data, timeout=timeout)
2020-12-11T06:37:18.764720+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 411, in _send
2020-12-11T06:37:18.764720+00:00 app[web.1]:     RPCError.raise_it(result, type(data))
2020-12-11T06:37:18.764721+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
2020-12-11T06:37:18.764721+00:00 app[web.1]:     raise getattr(
2020-12-11T06:37:18.764722+00:00 app[web.1]: pyrogram.errors.exceptions.bad_request_400.ButtonUrlInvalid: [400 BUTTON_URL_INVALID]: The button url is invalid (caused by "messages.SendMessage")
2020-12-11T06:37:28.803969+00:00 app[web.1]: 2020-12-11 06:37:28,803 - pyrogram.syncer - INFO - Synced ":memory:" in 2.10333 ms

**Comment by eyaadh** [comment]
Seems like the FQDN you have used is wrong, please share the environmental variables and more context for us to be of any further help

**Comment by IamJithendra** [comment]
I set WEB_SERVER_FQDN as my Heroku app link https://megatronxbot.herokuapp.com

**Comment by eyaadh** [comment]
Change it without https:// the application adds it.

https://github.com/eyaadh/megadlbot_oss/blob/a76cb4cd12df34bc7250e0394e8269df7bfe1adc/mega/helpers/uploader.py#L205
