### ISSUE TITLE
help............

### ISSUE THREAD

**Issue by WeebZoneIndia** [eyaadh/megadlbot_oss#60]
2021-04-07T05:34:57.455513+00:00 app[web.1]: 2021-04-07 05:34:57,455 - pyrogram.dispatcher - ERROR - argument of type 'int' is not iterable
2021-04-07T05:34:57.455536+00:00 app[web.1]: Traceback (most recent call last):
2021-04-07T05:34:57.455536+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 208, in handler_worker
2021-04-07T05:34:57.455537+00:00 app[web.1]:     await handler.callback(self.client, *args)
2021-04-07T05:34:57.455537+00:00 app[web.1]:   File "/app/mega/telegram/plugins/common.py", line 43, in stop_user_from_doing_anything
2021-04-07T05:34:57.455538+00:00 app[web.1]:     if allowed_users and message.from_user.id not in allowed_users:
2021-04-07T05:34:57.455539+00:00 app[web.1]: TypeError: argument of type 'int' is not iterable

**Comment by phoenixatom** [comment]
allowed_users must be a list. Put your user id in a list ([12345678])

**Comment by WeebZoneIndia** [comment]
ok
